/* ============================================================
   RE UP Report — Newsroom Feed Consumer
   Reads from data/exports/newsroom.json (generated by the
   newsroom pipeline: node newsroom/run.js)

   Desk-to-filter mapping:
     all          → everything
     clt-local    → Charlotte Local
     national-biz → National Barber Business
     supply-chain → Supply Chain
     clt-events   → Charlotte Events
   ============================================================ */

(function () {
  // Desk metadata for rendering
  var DESK_META = {
    'clt-local':    { tagClass: 'news-tag--charlotte', label: 'CLT Local' },
    'national-biz': { tagClass: 'news-tag--national',  label: 'National' },
    'supply-chain': { tagClass: 'news-tag--supply',    label: 'Supply Chain' },
    'clt-events':   { tagClass: 'news-tag--events',    label: 'CLT Events' }
  };

  var cachedArticles = [];
  var currentFilter = 'all';

  // Detect base path (works from / and /pages/)
  function getApiBase() {
    var loc = window.location.pathname;
    if (loc.indexOf('/pages/') !== -1) return '../';
    return './';
  }

  // Fetch newsroom.json from the data exports
  function fetchFeed() {
    var base = getApiBase();
    return fetch(base + 'data/exports/newsroom.json')
      .then(function (res) {
        if (!res.ok) throw new Error('Newsroom feed not found');
        return res.json();
      })
      .then(function (feed) {
        return feed.articles || [];
      });
  }

  // Render an impact badge
  function impactBadge(impact) {
    if (!impact || impact === 'low') return '';
    var cls = impact === 'high' ? 'news-impact--high' : 'news-impact--medium';
    return '<span class="news-impact ' + cls + '">' + impact.toUpperCase() + '</span>';
  }

  // Render articles into the grid
  function renderNewsCards(articles) {
    var grid = document.getElementById('news-grid');
    if (!grid) return;

    if (articles.length === 0) {
      grid.innerHTML = '<div class="news-empty">No stories from this desk yet. Run <code>node newsroom/run.js</code> to gather intelligence.</div>';
      return;
    }

    var html = '';
    for (var i = 0; i < articles.length; i++) {
      var a = articles[i];
      var meta = DESK_META[a.desk] || { tagClass: 'news-tag--charlotte', label: a.desk };

      // Format date nicely
      var displayDate = a.date || '';
      try {
        var d = new Date(a.date);
        if (!isNaN(d.getTime())) {
          displayDate = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        }
      } catch (e) { /* keep raw */ }

      html +=
        '<div class="news-card" data-desk="' + a.desk + '" data-score="' + (a.score || 0) + '">' +
          '<div class="news-card-header">' +
            '<span class="news-tag ' + meta.tagClass + '">' + meta.label + '</span>' +
            '<span class="news-date">' + displayDate + '</span>' +
          '</div>' +
          '<h3 class="news-title">' + escapeHtml(a.title) + '</h3>' +
          '<p class="news-summary">' + escapeHtml(a.summary) + '</p>' +
          '<div class="news-source">' +
            '<span>' + escapeHtml(a.source) + '</span>' +
            ' &middot; ' +
            '<a href="' + encodeURI(a.url) + '" target="_blank" rel="noopener noreferrer">Read article</a>' +
            impactBadge(a.impact) +
          '</div>' +
        '</div>';
    }

    grid.innerHTML = html;
  }

  function escapeHtml(str) {
    var div = document.createElement('div');
    div.textContent = str || '';
    return div.innerHTML;
  }

  // Apply the current filter to cached articles
  function applyFilter(filter) {
    currentFilter = filter;
    var filtered = filter === 'all'
      ? cachedArticles
      : cachedArticles.filter(function (a) { return a.desk === filter; });
    renderNewsCards(filtered);
  }

  // Wire up filter tabs
  function initNewsTabs() {
    var tabs = document.querySelectorAll('[data-news-filter]');
    for (var i = 0; i < tabs.length; i++) {
      tabs[i].addEventListener('click', function () {
        var siblings = this.parentElement.querySelectorAll('.news-tab');
        for (var j = 0; j < siblings.length; j++) {
          siblings[j].classList.remove('active');
        }
        this.classList.add('active');
        applyFilter(this.getAttribute('data-news-filter'));
      });
    }
  }

  function init() {
    fetchFeed()
      .then(function (articles) {
        cachedArticles = articles;
        applyFilter('all');
      })
      .catch(function () {
        // Feed not generated yet — show guidance
        var grid = document.getElementById('news-grid');
        if (grid) {
          grid.innerHTML = '<div class="news-empty">Newsroom feed not generated yet.<br>Run <code>node newsroom/run.js</code> to populate.</div>';
        }
      });
    initNewsTabs();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
